### ISSUE TITLE
How use it?

### ISSUE THREAD

**Issue by Spec86** [csfulop/sicp_java#1]
Hello, how use it app? My Laptop use Windows 10.

**Comment by csfulop** [comment]
Hi @Spec86,
This is the source code of a java project. It uses the maven build tool.
There are many ways to run a java project.
The most simple is to install maven and run:
`mvn exec:java -Dexec.mainClass="com.github.csfulop.sicpjava.lisp.ReadEvalPrintLoop"`
See TestReadEvalPrintLoop.java file for some example.
